### ISSUE TITLE
Linking issue in Linux x86_64

### ISSUE THREAD

**Issue by ppurka** [emil79/flagmatic#1]
Hello,
  I have been trying to install flagmatic on Linux, but I am running in to the following problem. I am unable to import it from inside Sage. The steps I performed are as follows:
1. Compile using `sage --python setup.py install`. The compilation proceeds fine and it correctly installs flagmatic. The compile log can be [found here](https://gist.github.com/ppurka/6a573cd7675e1afe6261#file-flagmatic_compile-log).
2. When importing flagmatic it gives the error that it can't find `_signals`:

```
    ----------------------------------------------------------------------
    | Sage Version 5.7.beta0, Release Date: 2013-01-23                   |
    | Type "notebook()" for the browser-based notebook interface.        |
    | Type "help()" for help.                                            |
    ----------------------------------------------------------------------
    **********************************************************************
    *                                                                    *
    * Warning: this is a prerelease version, and it may be unstable.     *
    *                                                                    *
    **********************************************************************
    sage: from flagmatic.all import *
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)

    /home/ppurka/<ipython console> in <module>()

    /home/ppurka/Installations/sage-5.7.beta0.flagmatic/local/lib/python2.7/site-packages/flagmatic/all.py in <module>()
         29 
         30 from flag import *
    ---> 31 from hypergraph_flag import *
         32 from three_graph_flag import *
         33 from graph_flag import *

    ImportError: /home/ppurka/Installations/sage-5.7.beta0.flagmatic/local/lib/python2.7/site-packages/flagmatic/hypergraph_flag.so: undefined symbol: _signals
    sage: 
```
1. I have tried adding `"-lcsage"` to the `extra_compile_args` in `setup.py`, explicitly providing path to the `libcsage.so` file, and many other ways to make it link to `libcsage` properly, but none of them work.
2. If I change to the flagmatic directory in `SAGE_ROOT/local/lib/python/site-packages` and look at the symbols in the `hypgraph_flag` file, I get a lot of undefined symbols. `_signals` and a bunch of `sig` functions are among them. The whole output can be [seen here](https://gist.github.com/ppurka/6a573cd7675e1afe6261#file-undefined_symbols-txt).
3. `LD_LIBRARY_PATH` seems properly defined inside the sage shell.

```
    ...7/site-packages/flagmatic» echo $SAGE_ROOT
/home/ppurka/Installations/sage-5.7.beta0.flagmatic
    ...7/site-packages/flagmatic» echo $LD_LIBRARY_PATH
/home/ppurka/Installations/sage-5.7.beta0.flagmatic/local/lib:/home/ppurka/Installations/sage-5.7.beta0.flagmatic/local/lib/R/lib
```

Perhaps you have a better idea of why it is unable to link properly? I installed flagmatic on to a friend's OSX 10.6.8 and it installed and runs without any problems there.

**Comment by ppurka** [comment]
Update: on my friend's OSX the undefined symbols are slightly different. `__signals` is undefined there (note the extra underscore). The output of `nm hypergraph_flag.so | grep -w 'U'` is [present here](https://gist.github.com/ppurka/6a573cd7675e1afe6261#file-undefined_symbols_osx-txt).

But flagmatic works on that installation.

**Comment by emil79** [comment]
Thanks for reporting this! Perhaps we can remove signals entirely from Flagmatic: I followed instructions and tried to use sig_on and sig_off so that Ctrl-C would be handled properly (but it never really worked). If you have time, would you be able to do this, and see if that fixes the problem? I'd really like to see Flagmatic working on Linux.

**Comment by ppurka** [comment]
Thanks for your suggestion. I never thought about removing the signals code! It is so simple to get it to import in Linux, after I removed the signals code. :)

**Comment by emil79** [comment]
Thanks @ppurka, I've merged your PR. Please continue to contribute! Examples, improvements, etc...

**Comment by ppurka** [comment]
Thanks! I have just started reading this topic.

I suppose you can close this ticket now.
